Add support for bazel buildsystem to physics3
ignitionrobotics/ign-physics pull request #157
Opened 2020-11-10 21:29 UTC by mjcarroll

2020-11-18 19:29 UTC, mahiuchun commented on dartsim/BUILD.bazel
> +    srcs = [":dartsim"],
use deps instead of srcs?

2020-11-18 19:29 UTC, mahiuchun commented on tpe/BUILD.bazel
> +    srcs = [":plugin"],
use deps instead of srcs?

2020-12-09 18:37 UTC, mahiuchun commented on test/PhysicsPluginsList.hh
> +  auto it = _path.find("__main__");
turns out our internal version of Bazel does not use `__main__` in its paths. could we only check the existence of `TEST_SRCDIR`?

2021-04-15 18:12 UTC, mahiuchun approved these changes

2021-08-17 00:46 UTC, chapulina requested changes
CI is broken

2021-11-12 18:02 UTC, chapulina commented
I believe this PR is outdated and not being worked on. Please reopen if this starts being worked on again.

2021-11-12 18:02 UTC, closed without merging