[Citadel] Update tutorials
ignitionrobotics/ign-physics pull request #204
Opened 2021-01-22 20:17 UTC by claireyywang

- Use Doxygen code snippet and image 
- Add example code
- Update tutorial titles and content

2021-01-22 20:24 UTC, claireyywang commented
@chapulina  I addressed your tutorial comments in this PR. Feel free to take a look if you have time .

2021-01-26 01:05 UTC, chapulina reviewed
Can we add a `CMakeLists` file to `examples/simple_tpe_plugin` so that it's possible to compile it?

2021-01-26 01:05 UTC, chapulina commented on tutorials/03_physics_plugins.md
> +\page physicsplugins Understand Physics Plugin
Note that changing the page name also changes the URL of the tutorial. Right now, the URL is https://ignitionrobotics.org/api/physics/3.1/physicsplugin.html. If we change them, anyone who had the old links on a website for example, will be left with broken links. So often it is better to stay with "bad" links that work for previous users, than to improve the URLs but break links.

These tutorials are relatively new though, so I think it's not too late to change them. I'll leave it up to you.

2021-01-26 01:05 UTC, chapulina commented on tutorials/02_installation.md
> +We recommend following the [binary installation](#Binary-installation) instructions to get up and running as quickly and painlessly as possible.
I think these links had been removed because now we have multiple sections for binary and source installation, according to the OS.

2021-01-26 01:05 UTC, chapulina commented on tutorials/02_installation.md
> -Be sure to replace `<#>` with a number value, such as `1` or `2`, depending on which version you need.
I think it's ok to leave as it was, which is easier to maintain in the long run. I believe it was changed on purpose.

2021-01-26 01:05 UTC, chapulina commented on tutorials/04_physics_engines.md
> +See [Physics engines](https://ignitionrobotics.org/api/gazebo/4.1/physics.html) in Ign-gazebo tutorial.
This is targeting Citadel, so it should use `ign-gazebo3`

2021-02-04 00:28 UTC, claireyywang commented
> Can we add a `CMakeLists` file to `examples/simple_tpe_plugin` so that it's possible to compile it?

I added an example `CMakeList` but don't think it's working correctly yet. I'm still not sure how exactly CMake links different libraries so it'd take some time to figure that out. I think it'd be preferable to merge the tutorial part of the this PR first, and take the CMake part out for later improvement. What do you think?

2021-02-09 20:57 UTC, chapulina requested changes
> I added an example CMakeList but don't think it's working correctly yet.

The plugin fails to compile for me with:

```
/home/chapulina/ws_citadel/src/ign-physics/examples/simple_tpe_plugin/plugin.cc:20:10: fatal error: Base.hh: No such file or directory
 #include "Base.hh"
          ^~~~~~~~~
```

Looking through the code, I imagine this is supposed to refer to [tpe/plugin/src/Base.hh](https://github.com/ignitionrobotics/ign-physics/blob/ign-physics3/tpe/plugin/src/Base.hh), right? The reason that the example is not being able to find it, is that the header isn't being installed. I suspect this is on purpose though, because we don't need downstream users to be using `tpe-plugin`, only `tpe-lib`, right? I haven't looked closely enough to have a suggestion here, but I think that the example needs to be reworked to only use things from `tpe-lib`, not `tpe-plugin`.

> I think it'd be preferable to merge the tutorial part of the this PR first, and take the CMake part out for later improvement.

I think that the CMake failure exposed a potential problem in the tutorial. I think it's worth it getting it to work before we publish it, so we're sure we're giving users working instructions.

2021-02-09 20:57 UTC, chapulina commented on tutorials/09_use_custom_engine.md
> +│   │    |     ├── <FEATURES_TEST>.cc    Tests
```suggestion
│   │    |     └── <FEATURES_TEST>.cc    Tests
```

Nitpick :grin: The same on the next line.

2021-02-09 20:57 UTC, chapulina commented on tutorials/09_use_custom_engine.md
> +interfacing with the physics engine API inside `plugin\src` folder
```suggestion
interfacing with the physics engine API inside `plugin/src` folder
```

2021-05-03 22:14 UTC, chapulina approved these changes
I pushed some tweaks to:

* Make the example and test compile
* Maintain the current tutorial URLs, so we don't break existing links to the site
* Fix snippets

LGTM!

2021-05-03 22:15 UTC, merged