Remove implicit-defined copy constructor/operator
ignitionrobotics/ign-physics pull request #328
Opened 2022-03-08 20:33 UTC by mjcarroll

Cleans up warnings eg:

```
/home/mjcarroll/workspaces/ign_garden/src/ign-physics/tpe/lib/src/Shape.cc: In copy constructor ‘ignition::physics::tpelib::CapsuleShape::CapsuleShape(const ignition::physics::tpelib::CapsuleShape&)’:
/home/mjcarroll/workspaces/ign_garden/src/ign-physics/tpe/lib/src/Shape.cc:98:11: warning: implicitly-declared ‘ignition::physics::tpelib::CapsuleShape& ignition::physics::tpelib::CapsuleShape::operator=(const ignition::physics::tpelib::CapsuleShape&)’ is deprecated [-Wdeprecated-copy]
   98 |   *this = _other;
      |           ^~~~~~
```

Signed-off-by: Michael Carroll <michael@openrobotics.org>.

2022-03-08 20:44 UTC, ahcorde requested changes
do we need to tick-tock this methods?

2022-03-08 20:44 UTC, ahcorde commented on tpe/lib/src/Shape.cc
> + *
?

2022-03-08 20:54 UTC, mjcarroll commented on tpe/lib/src/Shape.cc
> + *
Whoops.

2022-03-08 20:56 UTC, mjcarroll commented
> do we need to tick-tock this methods?

The corresponding methods should be created by the compiler in these cases.

Furthermore, I'm not entirely convinced that some of these were doing the right thing.  The assignment operator is assuming that the RHS was of the same type, even when that wouldn't have been the same.

2022-03-08 21:28 UTC, mjcarroll commented
Not a great sign from codecov, either :sweat_smile: 

```
+ Misses       1398     1370      -28     
```

2022-03-08 21:57 UTC, azeey approved these changes

2022-03-09 18:04 UTC, scpeters approved these changes

2022-03-10 20:05 UTC, merged